type User @collection(name: "users") {
  profile_id: Int! @unique
  slug: String! @unique
  username: String!
  first_name: String!
  last_name: String!
  full_name: String!
  avatar: String!
  channel_count: Int!
  initials: String!
  is_premium: Boolean!
  is_exceeding_private_connections_limit: Boolean!
}

type Metadata {
  description: String!
}

type Channel {
  id: String!
  title: String!
}

type Grove @collection(name: "groves") {
  id: ID!
  channel: Channel!
}

type Block {
  id: ID!
  content: String!
}

type Query {
  userByProfileID(profile_id: Int!): [User!]
}