type User @collection(name: "users") {
  id: ID!
  profile_id: String!
  slug: String!
  username: String!
  first_name: String!
  last_name: String!
  full_name: String!
  avatar: String!
  avatar_image: Avatar
  channel_count: Int!
  initials: String!
  is_premium: Boolean!
  is_exceeding_private_connections_limit: Boolean!
  badge: String!
}

type Avatar {
  thumb: String!
  display: String!
}

type Metadata {
  description: String!
}

type Channel {
  id: String!
  title: String!
}

type Grove @collection(name: "groves") {
  id: ID!
  channel: Channel!
}

type Block {
  id: ID!
  content: String!
}